:jdk: https://openjdk.java.net/install/
:toc:
:icons: font
:source-highlighter: prettify
:project_id: gs-maven

This guide walks you through using Maven to build a simple Java project.

== What you'll build

You'll create an application that provides the time of day and then build it with Maven.

== What you'll need

 - About 15 minutes
 - A favorite text editor or IDE
 - {jdk}[JDK 8] or later

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/how_to_complete_this_guide.adoc[]

[[scratch]]
== Set up the project

First you'll need to setup a Java project for Maven to build. To keep the focus on Maven, make the project as simple as possible for now. Create this structure in a project folder of your choosing.

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/create_directory_structure_hello.adoc[]


Within the `src/main/java/hello` directory, you can create any Java classes you want. To maintain consistency with the rest of this guide, create these two classes: `HelloWorld.java` and `Greeter.java`.

`src/main/java/hello/HelloWorld.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/hello/HelloWorld.java[]
----

`src/main/java/hello/Greeter.java`
[source,java,tabsize=2]
----
include::initial/src/main/java/hello/Greeter.java[]
----


[[initial]]

Now that you have a project that is ready to be built with Maven, the next step is to install Maven.

Maven is downloadable as a zip file at https://maven.apache.org/download.cgi. Only the binaries are required, so look for the link to apache-maven-_{version}_-bin.zip or apache-maven-_{version}_-bin.tar.gz.

Once you have downloaded the zip file, unzip it to your computer. Then add the _bin_ folder to your path.

To test the Maven installation, run `mvn` from the command-line:

----
mvn -v
----

If all goes well, you should be presented with some information about the Maven installation. It will look similar to (although perhaps slightly different from) the following:

....
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T16:41:47+00:00)
Maven home: /home/dsyer/Programs/apache-maven
Java version: 1.8.0_152, vendor: Azul Systems, Inc.
Java home: /home/dsyer/.sdkman/candidates/java/8u152-zulu/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-36-generic", arch: "amd64", family: "unix"
....

Congratulations! You now have Maven installed.

INFO: You might like to consider using the https://github.com/takari/maven-wrapper[Maven wrapper] to insulate your developers against having the correct version of Maven, or having to install it at all. Projects downloaded from https://start.spring.io[Spring Initializr] have the wrapper included. It shows up as a script `mvnw` in the top level of your project which you run in place of `mvn`.


== Define a simple Maven build

Now that Maven is installed, you need to create a Maven project definition. Maven projects are defined with an XML file named _pom.xml_. Among other things, this file gives the project's name, version, and dependencies that it has on external libraries.

Create a file named _pom.xml_ at the root of the project (i.e. put it next to the `src` folder) and give it the following contents:

`pom.xml`
[source,xml]
----
include::initial/pom.xml[]
----

With the exception of the optional `<packaging>` element, this is the simplest possible _pom.xml_ file necessary to build a Java project. It includes the following details of the project configuration:

* `<modelVersion>`. POM model version (always 4.0.0).
* `<groupId>`. Group or organization that the project belongs to. Often expressed as an inverted domain name.
* `<artifactId>`. Name to be given to the project's library artifact (for example, the name of its JAR or WAR file).
* `<version>`. Version of the project that is being built.
* `<packaging>` - How the project should be packaged. Defaults to "jar" for JAR file packaging. Use "war" for WAR file packaging.

NOTE: When it comes to choosing a versioning scheme, Spring recommends the https://semver.org[semantic versioning] approach.

At this point you have a minimal, yet capable Maven project defined.

== Build Java code
Maven is now ready to build the project. You can execute several build lifecycle goals with Maven now, including goals to compile the project's code, create a library package (such as a JAR file), and install the library in the local Maven dependency repository.

To try out the build, issue the following at the command line:

----
mvn compile
----

This will run Maven, telling it to execute the _compile_ goal. When it's finished, you should find the compiled _.class_ files in the _target/classes_ directory.

Since it's unlikely that you'll want to distribute or work with _.class_ files directly, you'll probably want to run the _package_ goal instead:

----
mvn package
----

The _package_ goal will compile your Java code, run any tests, and finish by packaging the code up in a JAR file within the _target_ directory. The name of the JAR file will be based on the project's `<artifactId>` and `<version>`. For example, given the minimal _pom.xml_ file from before, the JAR file will be named _{project_id}-0.1.0.jar_.

To execute the JAR file run:

----
java -jar target/gs-maven-0.1.0.jar
----

NOTE: If you've changed the value of `<packaging>` from "jar" to "war", the result will be a WAR file within the _target_ directory instead of a JAR file.

Maven also maintains a repository of dependencies on your local machine (usually in a _.m2/repository_ directory in your home directory) for quick access to project dependencies. If you'd like to install your project's JAR file to that local repository, then you should invoke the `install` goal:

----
mvn install
----

The _install_ goal will compile, test, and package your project's code and then copy it into the local dependency repository, ready for another project to reference it as a dependency.

Speaking of dependencies, now it's time to declare dependencies in the Maven build.

== Declare Dependencies

The simple Hello World sample is completely self-contained and does not depend on any additional libraries. Most applications, however, depend on external libraries to handle common and complex functionality.

For example, suppose that in addition to saying "Hello World!", you want the application to print the current date and time. While you could use the date and time facilities in the native Java libraries, you can make things more interesting by using the Joda Time libraries.

First, change HelloWorld.java to look like this:

`src/main/java/hello/HelloWorld.java`
[source,java,tabsize=2]
----
include::complete/src/main/java/hello/HelloWorld.java[]
----

Here `HelloWorld` uses Joda Time's `LocalTime` class to get and print the current time.

If you were to run `mvn compile` to build the project now, the build would fail because you've not declared Joda Time as a compile dependency in the build. You can fix that by adding the following lines to _pom.xml_ (within the `<project>` element):

[source,xml,indent=0]
----
<dependencies>
include::complete/pom.xml[tag=joda]
</dependencies>
----

This block of XML declares a list of dependencies for the project. Specifically, it declares a single dependency for the Joda Time library. Within the `<dependency>` element, the dependency coordinates are defined by three sub-elements:

* `<groupId>` - The group or organization that the dependency belongs to.
* `<artifactId>` - The library that is required.
* `<version>` - The specific version of the library that is required.

By default, all dependencies are scoped as `compile` dependencies. That is, they should be available at compile-time (and if you were building a WAR file, including in the _/WEB-INF/libs_ folder of the WAR). Additionally, you may specify a `<scope>` element to specify one of the following scopes:

* `provided` - Dependencies that are required for compiling the project code, but that will be provided at runtime by a container running the code (e.g., the Java Servlet API).
* `test` - Dependencies that are used for compiling and running tests, but not required for building or running the project's runtime code.

Now if you run `mvn compile` or `mvn package`, Maven should resolve the Joda Time dependency from the Maven Central repository and the build will be successful.

== Write a Test

First add JUnit as a dependency to your pom.xml, in the test scope:

[source,xml,indent=0]
----
include::complete/pom.xml[tag=junit]
----

Then create a test case like this:

`src/test/java/hello/GreeterTest.java`
[source,java,tabsize=2]
----
include::complete/src/test/java/hello/GreeterTest.java[]
----

Maven uses a plugin called "surefire" to run unit tests. The default configuration of this plugin compiles and runs all classes in `src/test/java` with a name matching `*Test`. You can run the tests on the command line like this

----
mvn test
----

or just use `mvn install` step as we already showed above (there is a lifecycle definition where "test" is included as a stage in "install").

Here's the completed `pom.xml` file:

`pom.xml`
[source,xml]
----
include::complete/pom.xml[]
----

NOTE: The completed **pom.xml** file is using the https://maven.apache.org/plugins/maven-shade-plugin/[Maven Shade Plugin]
for the simple convenience of making the JAR file executable. The focus of this guide is getting started with Maven,
not using this particular plugin.

== Summary
Congratulations! You've created a simple yet effective Maven project definition for building Java projects.

== See Also

The following guides may also be helpful:

* https://spring.io/guides/gs/gradle/[Building Java Projects with Gradle]

include::https://raw.githubusercontent.com/spring-guides/getting-started-macros/master/footer.adoc[]
